DROP TABLE IF EXISTS endereco;
DROP TABLE IF EXISTS cliente;
DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario
(
	id_usuario BIGSERIAL NOT NULL PRIMARY KEY,
	login CHARACTER VARYING(40) NOT NULL UNIQUE,
	email CHARACTER VARYING(40) NOT NULL UNIQUE,
	senha CHARACTER VARYING(32) NOT NULL,
	excluido CHARACTER VARYING(3),
	data_exclusao date
);

CREATE TABLE cliente
(
	id_usuario BIGINT NOT NULL PRIMARY KEY REFERENCES usuario,
	nome CHARACTER VARYING(30) NOT NULL,
	sobrenome CHARACTER VARYING(40) NOT NULL,
	cpf CHARACTER VARYING(14) NOT NULL UNIQUE,
	sexo CHARACTER VARYING(1) NOT NULL,
	data_nasc DATE NOT NULL,
	telefone CHARACTER VARYING(14),
	celular CHARACTER VARYING(14),
	excluido CHARACTER VARYING(3),
	data_exclusao DATE
);

CREATE TABLE endereco
(
	id_endereco SERIAL NOT NULL PRIMARY KEY,
	id_usuario BIGSERIAL NOT NULL REFERENCES cliente,
	endereco CHARACTER VARYING(100) NOT NULL,
	numero CHARACTER VARYING(10) NOT NULL,
	complemento CHARACTER VARYING(40),
	bairro CHARACTER VARYING(40),
	cep CHARACTER VARYING(10) NOT NULL,
	cidade CHARACTER VARYING(40) NOT NULL,
	estado CHARACTER VARYING(2) NOT NULL,
	pais CHARACTER VARYING(30) NOT NULL,
	excluido CHARACTER VARYING(3),
	data_exclusao DATE
);
